### ISSUE TITLE
Chat example errors when I run with python3.6.3

### ISSUE THREAD

**Issue by csunny** [zixuanzh/py-libp2p#68]
There has some errors in the code of chat example when i run with python3.6,  and the error just like this

```
python3 chat.py --port 3001 -d /ip4/127.0.0.1/tcp/3000/p2p/2d37wbGvQzbAQ84yRouh2m2vBKkN8s5AfH9Q75HZRCUQmJW7yAVSNKzjJj6gcjE2mDNDUHCichXWdMH3S2c8AaDLm3kXmf5R8D5dDg7mMksSs28iX8EnFs7nAHEg6T2xFcg35M8sNmf7arzjFoMW8Vseaykx9c21Hy5RiTxmGZw12urzdAZHgrWZptnVR6Qsr3HAuuKqdENr1PxEjdVdmBL3Gi6iNhYeED9PWLi7noNFF8bvfSY5wmY6ys7oXABtJXeu8dC6Jd5sm3nvUDRFXarUXNLfpAQNRDyuVGvDUVR3DRQVw3btt9pQXmmmaHwzFtxxL5qijZqgbrRdmFrdC5HgyiYs8rB5hbSDpCeRNaD8BtMdtyzSAn8Qt8bTNSYSeBsGveFQU8ovHQ4gLFmKkBdvVLe5pFVdRAnVN6GFAZrWQdWsUh6kEhy2q7R2zRjK6UF4oL5dqmw9eoWmXgzNYfmji1oQSx6DxNNpcdvKM7apEzeX6KQANRbLgn7VkGwoU3eZv2qoHEzWpULp5K6i4hz7Tab12ovct9uQKSFdCoKE7Qp34dhR5sExhns3GyytwiqfySZ7YAsctNRPAwoTTLNGBN3ZQfD4Agvf2Ck
timeout!
Task exception was never retrieved
future: <Task finished coro=<read_data() done, defined at chat.py:16> exception=KeyError(1532609824184786476,)>
Traceback (most recent call last):
  File "chat.py", line 18, in read_data
    read_string = (await stream.read()).decode()
  File "/Users/magic/workspace/data/www/GitHub/py-libp2p/network/stream/net_stream.py", line 28, in read
    return await self.muxed_stream.read()
  File "/Users/magic/workspace/data/www/GitHub/py-libp2p/stream_muxer/mplex/mplex_stream.py", line 43, in read
    return await self.mplex_conn.read_buffer(self.stream_id)
  File "/Users/magic/workspace/data/www/GitHub/py-libp2p/stream_muxer/mplex/mplex.py", line 48, in read_buffer
    data = self.buffers[stream_id]
KeyError: 1532609824184786476
```

The hostA is ok, but when i run hostB, the error raise.

**Comment by csunny** [comment]
@robzajac   Thanks for your answer, it can't establish connection when i  run command in another terminal quickly.   The error like this

```
magic@magicdeMacBook-Pro:~/workspace/data/www/GitHub/py-libp2p/examples/chat$ ./chat.py --port 8001 -d /ip4/127.0.0.1/tcp/8000/p2p/2d37wbGvQzbAQ84yRouh2m2vBKkN8s5AfH9Q75HZRCUQmJW7yAVSNKzjJj6gcjE2mDNDUHCichXWdMH3S2c8AaDLm3kXmf5R8Ap7EGUPg2GxePFB2BEdtAxr7K5UWBQ4CkEWretg97iS6M9hrKRnMEfsHnxd6sLCssU4udRoJmLgsmypWDtJYPHcZn1nsAjxoZHpqtEDkMNboC7QmSXPwaDqRh7rju3YeHHZsxmomBoBZViKSWJzPTtDa4awU5yKK4WmzkhynCLfw11kwZ6gSvZmjDJ1SsakztafdDKZLkSJE3TxQekRqcfqGcVm2BpTLqaUu3BkJUTWT65zV9DZJThhJv6LuKKh4RFC7oSskAqztZNanA2siiVVPvfMPKaQyzkrbVMQ9sWsCqbz8gubmZQszhQxxh91w79SE1MQkagvffnBmSDGFKBhSF5S6WfxLULoEcXS1xhwtAuGsbVFnxv9EEx6jwTmBdtkHfNB1z3iijVfFcxp1ShoDv5FLpXXHxNqoUkCbkxhJUGrwAXQARrenR7im7j58RPGW3UUpMEZuyGRTip1QrRAQeBCxMTnUNDmRMgVxJwZ16hc7DWBGdEfnyEnR66nQAKFgix
Failed to connect to: <network.multiaddr.MultiAddr object at 0x10ec08240>
timeout!
Task exception was never retrieved
future: <Task finished coro=<read_data() done, defined at ./chat.py:16> exception=KeyError(1444027442205078353,)>
Traceback (most recent call last):
  File "./chat.py", line 18, in read_data
    read_string = (await stream.read()).decode()
  File "/Users/magic/workspace/data/www/GitHub/py-libp2p/network/stream/net_stream.py", line 28, in read
    return await self.muxed_stream.read()
  File "/Users/magic/workspace/data/www/GitHub/py-libp2p/stream_muxer/mplex/mplex_stream.py", line 43, in read
    return await self.mplex_conn.read_buffer(self.stream_id)
  File "/Users/magic/workspace/data/www/GitHub/py-libp2p/stream_muxer/mplex/mplex.py", line 48, in read_buffer
    data = self.buffers[stream_id]
KeyError: 1444027442205078353
```

And I know about the lib of py-libp2p is developing.  I meet this lib at yesterday, and i am reading the source code,  and try to fix this example error just by myself.    I am a fan of ipfs, i hope i can do someting for this project.   thanks for your reply again! @robzajac

**Comment by robzajac** [comment]
@csunny I'm unfortunately not totally sure what the problem could be - I see a "Failed to connect to:..." line being printed, which would happen upon an IOError in `Swarm.listen()`, and that error probably comes from the call to `start_server()` in `TCP.Listener.listen()`. That might suggest a machine-level problem while opening a socket on the specified port. 

Are you running the code from the `master` branch? Do the other tests in our `tests/` directory run successfully?

**Comment by csunny** [comment]
@robzajac  just as your say,  i am running the code from the master branch.  But when i run pytest command. some error raise.

```
================================================= test session starts ==================================================
platform darwin -- Python 3.6.3, pytest-4.0.0, py-1.7.0, pluggy-0.8.0
rootdir: /Users/magic/workspace/data/www/GitHub/py-libp2p/tests, inifile:
plugins: asyncio-0.9.0, celery-4.1.0
collected 23 items

test_example.py ......                                                                                           [ 26%]
libp2p/test_libp2p.py .                                                                                          [ 30%]
network/test_connection.py .                                                                                     [ 34%]
peer/test_addrbook.py .....                                                                                      [ 56%]
peer/test_peermetadata.py ....                                                                                   [ 73%]
peer/test_peerstore.py ......                                                                                    [100%]

============================================== 23 passed in 0.79 seconds ===============================================
Task was destroyed but it is pending!
task: <Task pending coro=<StreamReader.read() done, defined at /Users/magic/anaconda3/lib/python3.6/asyncio/streams.py:586> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11156f9d8>()]> cb=[_release_waiter(<Future pendi...11156fac8>()]>)() at /Users/magic/anaconda3/lib/python3.6/asyncio/tasks.py:316]>
Task was destroyed but it is pending!
task: <Task pending coro=<Swarm.listen.<locals>.conn_handler() running at /Users/magic/workspace/data/www/GitHub/py-libp2p/network/swarm.py:106> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x11156fac8>()]>>
```
Should i use ubuntu to run this code?  By the way, what's your developed machine and machine system?

**Comment by robzajac** [comment]
@csunny I don't get this error - are you running with `virtualenv` like described [here](https://github.com/zixuanzh/py-libp2p#development)? I see `celery-4.1.0` in the output above, which is not one of our current dependencies.

We haven't demo'd the library yet on Ubuntu. Most of our team is on macOS 10.14 on some edition of a MacBook Pro. What is your dev environment?

**Comment by robzajac** [comment]
Additionally - could we try running with Python 3.7 and see if that helps? We're seeing that Python 3.7 brought major improvements to `asyncio` and we have been developing with 3.7 - we will bump py-libp2p up soon.

**Comment by csunny** [comment]
@robzajac  
It's my fault.  I read the source code, and the error just because the next code 
[tcp](https://github.com/zixuanzh/py-libp2p/blob/master/transport/tcp/tcp.py)

```python
  coroutine = asyncio.start_server(self.handler, multiaddr_dict['host'],\
  multiaddr_dict['port'])
  self.server = await coroutine
```
It just when i start a socket server, i use a port which already used. so the next error raise.

```
Failed to connect to: <network.multiaddr.MultiAddr object at 0x10ec08240>
```

This example is running well in my env, not only  virtualenv but others now.
